"""Data contracts for the Hypothesis Generator pipeline.

Hypothesis captures scored, grounded code improvement hypotheses
generated from research-to-code correlations via a reflection loop
(HG-01, HG-03, HG-05).
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class HypothesisScores:
    """Inline scores for a hypothesis (HG-03).

    Scores are integers 1-10, generated by the LLM.
    """

    relevance: int
    """How relevant this hypothesis is to the research claims (1-10)."""

    feasibility: int
    """How feasible this is to implement (1-10)."""

    evidence: int
    """How strong the evidence from papers is (1-10)."""


@dataclass
class Hypothesis:
    """A code improvement hypothesis grounded in research-to-code correlations.

    The ``id`` is a deterministic SHA-256 hash of title+description (AD-02).
    The ``composite`` score is the arithmetic mean of relevance, feasibility,
    and evidence (equal weighting per brainstorming D2).

    Fields (HG-01):
        id: Deterministic SHA-256 hex digest truncated to 12 chars.
        title: Concise specific title (5-10 words).
        description: Detailed explanation of the hypothesis (2-4 sentences).
        approach: Specific technical approach to implement or test.
        supporting_papers: List of paper titles supporting this hypothesis.
        target_metric: What metric would improve if correct.
        expected_improvement: Qualitative description of expected improvement.
        code_changes: Specific code files/components that would change.
        scores: Relevance, feasibility, evidence scores (1-10).
        composite: Arithmetic mean of the three scores.
        correlations: List of synthetic correlation IDs grounding this hypothesis.
        success_criteria: Measurable criteria to validate this hypothesis.
    """

    id: str
    """Deterministic SHA-256 hex digest truncated to 12 chars (AD-02)."""

    title: str
    """Concise specific title (5-10 words)."""

    description: str
    """Detailed explanation (2-4 sentences)."""

    approach: str = ""
    """Specific technical approach to implement or test (1-3 sentences)."""

    supporting_papers: list[str] = field(default_factory=list)
    """Paper titles supporting this hypothesis."""

    target_metric: str = ""
    """Metric that would improve if the hypothesis is correct."""

    expected_improvement: str = ""
    """Qualitative description of expected improvement."""

    code_changes: str = ""
    """Specific code files/components that would change."""

    scores: HypothesisScores = field(
        default_factory=lambda: HypothesisScores(
            relevance=1, feasibility=1, evidence=1,
        )
    )
    """Relevance, feasibility, evidence scores (1-10)."""

    composite: float = 0.0
    """Arithmetic mean of relevance, feasibility, evidence (equal weighting)."""

    correlations: list[str] = field(default_factory=list)
    """Synthetic correlation IDs grounding this hypothesis (HG-05)."""

    success_criteria: str = ""
    """Measurable criteria to validate this hypothesis."""


@dataclass
class HypothesisResult:
    """Aggregation of hypotheses across all paper-clusters and reflection rounds.

    Never empty on the happy path — always contains metadata even when
    all generation fails (HG-06).

    Fields (HG-01):
        hypotheses: Successfully generated and grounded hypotheses.
        total_input_papers: Number of paper-clusters processed.
        total_correlations: Number of input correlations from CorrelationMap.
        reflection_rounds_completed: Number of reflection rounds executed (0-based — 0 means initial pass only).
        converged: Whether convergence was detected before max rounds.
        errors: Failure metadata for degraded outputs.
    """

    hypotheses: list[Hypothesis] = field(default_factory=list)
    """Successfully generated and grounded hypotheses."""

    total_input_papers: int = 0
    """Number of paper-clusters processed."""

    total_correlations: int = 0
    """Number of input correlations from CorrelationMap."""

    reflection_rounds_completed: int = 0
    """Number of reflection rounds executed (0 = initial pass only)."""

    converged: bool = False
    """Whether convergence was detected before max rounds."""

    errors: list[HypothesisError] = field(default_factory=list)
    """Failure metadata for degraded outputs."""


@dataclass
class HypothesisError:
    """Metadata about a failure during the hypothesis pipeline.

    Follows the same pattern as ``CorrelationError``, ``ProfilingError``,
    and ``RankingError``.
    """

    message: str
    """Human-readable error description."""

    exception_type: str | None = None
    """Python exception class name for debugging."""
